"""INTERNAL reader for the catalogue manifest: not part of the public API.

Plan decision D8 (W0.2 of the interface-system delivery plan): the catalogue
manifest (``static/brickwork/dist/catalogue-manifest.json``) is a SIBLING of
``template-manifest.json``, generated by ``scripts/generate_catalogue_manifest.py``
from the shipped template and examples trees. It is never merged into
``template-manifest.json``: that file is the versioned BR-BW-VER-001 contract
for block/partial names, while this one is descriptive catalogue metadata for
building a catalogue browsing/search surface (a site's gallery, principally),
documented as free to evolve in minors rather than semver-governed.

**The underscore-prefixed module name is deliberate, not a placeholder.**
The SHIPPED JSON is the public contract here (D8), not a Python wrapper
around it: a consumer (a site's gallery, principally) reads
``catalogue-manifest.json`` directly off the installed package, exactly the
pattern brickworkui.com's own ``docs_app/gallery/manifest.py`` already
follows for ``template-manifest.json``. This module's only real consumers
are IN-PACKAGE (``tests/test_catalogue_manifest.py``'s drift test today, the
W0.3 archetype-test harness next), so there is no external caller this
module needs to serve as public API, and every identifier in it, including
``FamilyEntry``/``families()``, may carry "family" without touching owner
ruling O1: O1 governs package API identifiers, and nothing here is one
(``tests/_class_contract.py`` is this repo's existing precedent for an
underscore-prefixed, deliberately-internal module). If a genuine external
Python-API need for this data ever emerges, that is a new O1 boundary
question for the owner, not a reason to widen this module's exposure on a
review pass.

Read ``docs/CATALOGUE.md`` for the full information architecture this
supports, including two explicit Wave 0 scoping decisions recorded there:
render inputs are deliberately NOT carried by this manifest (section 7), and
per-family "planned"/wave status is deliberately NOT carried either, because
it is roadmap truth rather than package truth (section 8).

Internal surface (mirrors ``services/template_manifest.py``'s public shape,
kept private here for the reason above):
- ``items()`` -> every catalogue item, in manifest order.
- ``families()`` -> every family with shipped coverage, package-truth only.
- ``items_by_kind(kind)`` -> items filtered to one kind.
- ``item(name)`` -> one item by its manifest ``name``, or ``None``.
- ``manifest()`` -> the whole parsed manifest dict (escape hatch).
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib.resources import files
from typing import Literal, TypedDict

_MANIFEST_RESOURCE = "static/brickwork/dist/catalogue-manifest.json"

CatalogueKind = Literal["shell", "component", "section", "archetype", "skeleton"]


class FamilyEntry(TypedDict):
    """Shipped-coverage package truth for one family (docs/CATALOGUE.md ss8).

    Carries counts only: no status field and no wave assignment, both of
    which are roadmap truth read from ROADMAP.md instead, never baked into
    this versioned artefact.
    """

    name: str
    archetypeCount: int
    sectionCount: int


class CatalogueItem(TypedDict, total=False):
    """One shipped shell, component, section, archetype or skeleton.

    ``family`` is ``None`` for a shell or component (cross-family building
    blocks) and for the ``skeleton`` kind (``examples/base.html``, a raw
    document skeleton a consumer copies into their own project rather than a
    complete page belonging to any family); populated for every archetype and
    ``None`` for every section. Shells and components additionally carry
    ``consumption`` (``"tag"``/``"extend"``/``"include"``) and
    ``usedByArchetypes``/``usedBySections``/``usedBySkeleton`` (which shipped
    examples compose this item, split by the consuming example's own kind so
    a skeleton user is never mislabelled as an archetype or section user).
    Sections, archetypes and the skeleton additionally carry
    ``requiresContext`` (whether the example needs render-context data to
    show its real content, docs/CATALOGUE.md ss7) and ``composesItems`` (the
    shells/components the example itself pulls in).
    """

    name: str
    kind: CatalogueKind
    family: str | None
    templatePath: str
    docSource: str
    consumption: str
    usedByArchetypes: list[str]
    usedBySections: list[str]
    usedBySkeleton: list[str]
    requiresContext: bool
    composesItems: list[str]


@lru_cache(maxsize=1)
def manifest() -> dict:
    """The whole parsed catalogue manifest (cached; read once per process)."""
    raw = files("brickwork").joinpath(_MANIFEST_RESOURCE).read_text(encoding="utf-8")
    return json.loads(raw)


@lru_cache(maxsize=1)
def items() -> tuple[CatalogueItem, ...]:
    """Every catalogue item, in manifest (kind, then name) order."""
    return tuple(manifest()["items"])


@lru_cache(maxsize=1)
def families() -> tuple[FamilyEntry, ...]:
    """Every family with shipped coverage today (package truth only)."""
    return tuple(manifest()["families"])


def items_by_kind(kind: CatalogueKind) -> tuple[CatalogueItem, ...]:
    """Every item of one kind (``shell``/``component``/``section``/``archetype``)."""
    return tuple(entry for entry in items() if entry["kind"] == kind)


@lru_cache(maxsize=1)
def _items_by_name() -> dict[str, CatalogueItem]:
    return {entry["name"]: entry for entry in items()}


def item(name: str) -> CatalogueItem | None:
    """One catalogue item by its manifest ``name``, or ``None`` if unknown."""
    return _items_by_name().get(name)
