#!/usr/bin/env python3
"""Generate ``interaction-manifest.json``: the interaction contract surface.

Run from the repo root:

    python scripts/generate_interaction_manifest.py

BR-BW-VER-001 names five contract surfaces. Tokens and template blocks/
partials already have dedicated generated manifests. This script is the
ONLY thing that writes ``interaction-manifest.json``, the third sibling
covering the remaining three surfaces (icvoss/django-brickwork#229,
Option C):

- Alpine component names (``Alpine.data("Name")`` registrations)
- Dispatched event names (``bw:...`` CustomEvents / htmx triggers)
- HTMX target IDs the package owns as stable swap mount points
  (BR-BW-HTMX-005)

Extraction rules (source, never hand-maintained lists):

1. **Alpine names.** Parsed from ``frontend/src/js/index.js``, the single
   registration point named in that file's module docstring. Pattern:
   ``Alpine.data("Name", ...)``.

2. **Event names.** Parsed from every ``*.js`` file under
   ``frontend/src/js/`` after stripping ``//`` and ``/* ... */`` comments.
   A name is included when it appears as a string literal matching
   ``bw:[a-z0-9:-]+`` in a dispatch / CustomEvent / htmx.trigger /
   addEventListener / removeEventListener call site (the contract surface
   consumers listen for or fire via ``HX-Trigger``). Ternary branches that
   name two events (e.g. sidebar collapse/expand) contribute both literals.

3. **HTMX target IDs.** Literal ``id="bw-..."`` attributes in the shipped
   package template tree (``src/brickwork/templates/`` and the marketing
   templates root) whose identifier also appears as ``#bw-...`` inside an
   ``hx-target`` / ``hx-swap-oob`` (or ``data-hx-*``) attribute-shaped
   reference in the same tree, including template comment prose that
   documents the consumer call site. That intersection is exactly the
   stable swap mount points BR-BW-HTMX-005 intends (today:
   ``bw-modal-root``, ``bw-slide-over-root``, ``bw-toast-region``).

   Excluded by construction: ``hx-target="this"``; consumer-owned region
   ids; dynamically composed ids (``bw-tabpanel-{{...}}``, per-row ids);
   landmark / skip-link ids that are not HTMX swap targets (``bw-main``,
   ``bw-sidebar``, ``bw-docs-nav``): those carry ``id="bw-..."`` but never
   appear as an ``hx-target`` / ``hx-swap-oob`` selector.

``do not edit by hand``: this file is regenerated by this script; the
``test`` CI job re-runs it via ``tests/test_interaction_manifest.py`` and
fails the build on any diff, mirroring the template and token drift gates.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
DIST = SRC / "brickwork" / "static" / "brickwork" / "dist"
MANIFEST_PATH = DIST / "interaction-manifest.json"
JS_ROOT = REPO_ROOT / "frontend" / "src" / "js"
INDEX_JS = JS_ROOT / "index.js"

_TEMPLATE_ROOTS = (
    SRC / "brickwork" / "templates" / "brickwork",
    SRC / "brickwork" / "marketing" / "templates" / "brickwork_marketing",
)

_ALPINE_DATA_RE = re.compile(r'Alpine\.data\(\s*"(\w+)"')
_LINE_COMMENT_RE = re.compile(r"//.*?$", re.MULTILINE)
_BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
# Event string literals that participate in the contract: dispatch, CustomEvent,
# htmx.trigger, and the window HX-Trigger listeners that close overlays.
_EVENT_CALL_RE = re.compile(
    r"""(?:dispatch|CustomEvent|htmx\.trigger|addEventListener|removeEventListener)"""
    r"""\s*\([^;]*?(["'])(bw:[a-z0-9:-]+)\1""",
    re.DOTALL,
)
# Ternary / bare string literals naming bw: events inside a dispatch argument
# list (sidebar collapse/expand) when the call-site regex above already matched
# the outer dispatch but only captured one branch via non-greedy scan: a second
# pass collects every bw: literal on lines that also contain dispatch(.
_BW_LITERAL_RE = re.compile(r"""(["'])(bw:[a-z0-9:-]+)\1""")
_DISPATCH_LINE_RE = re.compile(r"\bdispatch\s*\(")

_LITERAL_ID_RE = re.compile(r'\bid="(bw-[a-z0-9-]+)"')
# Matches both live attributes and comment-prose call sites such as
# hx-target="#bw-modal-root" / hx-swap-oob="afterbegin:#bw-toast-region".
_HX_TARGET_RE = re.compile(
    r"""(?:hx-target|data-hx-target|hx-swap-oob|data-hx-swap-oob)"""
    r"""\s*=\s*["'][^"']*?#(bw-[a-z0-9-]+)"""
)


def _strip_js_comments(source: str) -> str:
    without_blocks = _BLOCK_COMMENT_RE.sub("", source)
    return _LINE_COMMENT_RE.sub("", without_blocks)


def _alpine_names() -> list[str]:
    text = INDEX_JS.read_text(encoding="utf-8")
    names = _ALPINE_DATA_RE.findall(text)
    if not names:
        raise ValueError(
            f"found zero Alpine.data(...) registrations in {INDEX_JS.relative_to(REPO_ROOT)}; "
            "has the registration point moved?"
        )
    # Preserve registration order; refuse duplicates (would be a bug in index.js).
    seen: set[str] = set()
    ordered: list[str] = []
    for name in names:
        if name in seen:
            raise ValueError(f"duplicate Alpine.data registration for {name!r} in index.js")
        seen.add(name)
        ordered.append(name)
    return ordered


def _event_names() -> list[str]:
    found: set[str] = set()
    for path in sorted(JS_ROOT.glob("*.js")):
        stripped = _strip_js_comments(path.read_text(encoding="utf-8"))
        for match in _EVENT_CALL_RE.finditer(stripped):
            found.add(match.group(2))
        # Captures both branches of ternaries inside dispatch(...), e.g.
        # dispatch(root, this.isCollapsed ? "bw:sidebar:collapse" : "bw:sidebar:expand")
        for line in stripped.splitlines():
            if not _DISPATCH_LINE_RE.search(line):
                continue
            for lit in _BW_LITERAL_RE.finditer(line):
                found.add(lit.group(2))
    if not found:
        raise ValueError(
            f"found zero bw:... event literals under {JS_ROOT.relative_to(REPO_ROOT)}; has the event namespace moved?"
        )
    return sorted(found)


def _iter_template_files():
    for root in _TEMPLATE_ROOTS:
        if not root.is_dir():
            continue
        yield from sorted(root.rglob("*.html"))


def _htmx_target_ids() -> list[str]:
    """Stable package-owned HTMX swap mount points (BR-BW-HTMX-005).

    See module docstring for the intersection rule and exclusions.
    """
    declared: set[str] = set()
    referenced: set[str] = set()
    for path in _iter_template_files():
        text = path.read_text(encoding="utf-8")
        declared.update(_LITERAL_ID_RE.findall(text))
        referenced.update(_HX_TARGET_RE.findall(text))
    targets = sorted(declared & referenced)
    if not targets:
        raise ValueError(
            "found zero package-owned HTMX target IDs; expected at least "
            "bw-modal-root, bw-slide-over-root, and bw-toast-region "
            "(BR-BW-HTMX-005). Check the extraction rule in this script's docstring."
        )
    return targets


def build_manifest() -> dict:
    alpine = _alpine_names()
    events = _event_names()
    htmx_targets = _htmx_target_ids()
    return {
        "$schema": "https://brickwork.icvoss.dev/interaction-manifest/v1",
        "version": 1,
        "description": (
            "brickwork interaction contract: Alpine.data component names, "
            "dispatched bw: event names, and package-owned HTMX target IDs "
            "(BR-BW-VER-001 / BR-BW-HTMX-005). Names are semver-public: "
            "renaming or removing one requires the BR-BW-VER-001 "
            "parallel-support cycle and a major bump, never a silent change. "
            "Generated by scripts/generate_interaction_manifest.py from "
            "frontend/src/js/ and the shipped template tree; do not edit by hand."
        ),
        "alpineComponents": [{"name": name} for name in alpine],
        "events": [{"name": name} for name in events],
        "htmxTargets": [{"id": target_id} for target_id in htmx_targets],
        "deprecated": [],
    }


def main() -> int:
    manifest = build_manifest()
    DIST.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(
        "interaction manifest written: "
        f"{len(manifest['alpineComponents'])} alpine, "
        f"{len(manifest['events'])} events, "
        f"{len(manifest['htmxTargets'])} htmx targets -> {MANIFEST_PATH}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
