#!/usr/bin/env python3
"""Generate ``catalogue-manifest.json``: the catalogue taxonomy surface (D8).

Run from the repo root, with the package importable:

    DJANGO_SETTINGS_MODULE=tests.settings PYTHONPATH=src:. \\
        python scripts/generate_catalogue_manifest.py

This is a SIBLING of ``template-manifest.json``, never merged into it (plan
decision D8, W0.2). ``template-manifest.json`` is the versioned BR-BW-VER-001
contract for block/partial names; this file is catalogue taxonomy for the
interface-system catalogue (families, archetypes, examples), which churns per
wave and is documented as descriptive rather than semver-governed. Nothing
here adds a public identifier: "family" is a data field and a JSON value only,
never a template tag name, CSS class, token, or Python public name (the D4/O1
vocabulary gate).

This script is the ONLY thing that writes ``catalogue-manifest.json``: it
walks the real shipped tree the same way ``generate_template_manifest.py``
does (Django's own template engine, compiled node tree, never a regex over
source text) and covers every shipped shell, component, section example and
archetype example.

Kinds (D4's catalogue nouns, mapped onto the four kinds this manifest
records):

- ``shell``: the 5 files under ``templates/brickwork/shell/`` and
  ``brickwork_marketing/shell/`` (``base`` included: every other shell
  extends it, and CHANGELOG 3.0.0 counts it as one of the five named shells).
- ``component``: 40 underscore-prefixed files under (recursively)
  ``templates/brickwork/components/`` and ``brickwork_marketing/
  components/`` (forms/_*.html and nav/_*.html are their own tag surface,
  not counted here). ROADMAP.md's original W0.2 baseline was 39; W0.4
  (icvoss/django-brickwork#228) shipped the 40th, ``_theme_switch.html``.
  All 40 are directly under their root today; a future nested one is still
  found (the scan is recursive) and still counted.
- ``section``: the 26 files under ``examples/sections/<type>/<variant>.html``
  (D4: a section EXAMPLE, one band, the copy-paste unit).
- ``archetype``: the 16 files under ``examples/`` that are a complete page
  (``base.html`` plus ``app/*``, ``auth/*``, ``marketing/*``): D4 promotes
  "archetype" as the one defined noun for a complete copyable page example.

26 sections + 16 archetypes = the 42 examples ROADMAP.md and the plan's exit
criteria count.

``family`` (catalogue taxonomy only, per O1) is derived from the shipped
example directory an archetype/section lives under (``app`` -> "Product
applications", ``auth`` -> "Transactional journeys", ``marketing`` ->
"Marketing and public web", matching the INTERFACE-SYSTEM.md family table).
Shells and components are cross-family building blocks: their ``family`` is
``null``, and their ``usedByArchetypes``/``usedBySections`` fields (see
below) say which shipped examples, and so which families, actually use them
today. ``examples/base.html`` is also cross-family (a raw document skeleton,
not tied to one family), so it is the one archetype with ``family: null``
too.

``usedByArchetypes`` (on shells, components and sections) and
``composesItems`` (on sections and archetypes, the inverse) are derived by
walking each example's compiled node tree for ``{% include %}``/
``{% extends %}`` targets AND ``{% bw_* %}`` tag calls (the tag-consumed
components, e.g. ``_button.html``, are never ``{% include %}``d directly, so
their usage only shows up as a tag call in the compiled node list). This is
mechanical provenance, not a hand-maintained cross-reference.

``requiresContext`` (sections and archetypes only) is derived from the same
compiled tree: an example "requires context" when at least one
``{% include ... with key=value %}`` argument's own token is a bare template
variable reference rather than a quoted string or bare number literal (the
value must then come from the render context, since Django templates have no
other way to define a name). This mirrors the ``brickwork`` skill's own
documented split ("Most render from an EMPTY context... the exceptions are
the ones whose content is a list of dicts a template cannot build inline").
Where ``requiresContext`` is true, ``docSource`` is where the exact expected
shape is documented in full (the example's own leading ``{% comment %}``,
per every shipped template's documented-contract convention); this manifest
deliberately ships no render-input data of its own (see docs/CATALOGUE.md,
"Render inputs: deferred by design").

``do not edit by hand``: this file is regenerated by this script; a drift
test re-runs it and fails CI on any diff (mirrors
``test_template_manifest.py``'s drift gate).
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
DIST = SRC / "brickwork" / "static" / "brickwork" / "dist"
MANIFEST_PATH = DIST / "catalogue-manifest.json"
TEMPLATE_MANIFEST_PATH = DIST / "template-manifest.json"

# Family labels exactly as INTERFACE-SYSTEM.md's family/archetype matrix
# spells them, keyed by the example tree's own directory name.
_FAMILY_BY_EXAMPLE_DIR = {
    "app": "Product applications",
    "auth": "Transactional journeys",
    "marketing": "Marketing and public web",
}

_SHELL_ROOTS = (
    ("brickwork", SRC / "brickwork" / "templates" / "brickwork" / "shell"),
    ("brickwork_marketing", SRC / "brickwork" / "marketing" / "templates" / "brickwork_marketing" / "shell"),
)
_COMPONENT_ROOTS = (
    ("brickwork", SRC / "brickwork" / "templates" / "brickwork" / "components"),
    ("brickwork_marketing", SRC / "brickwork" / "marketing" / "templates" / "brickwork_marketing" / "components"),
)


def _setup_django() -> None:
    import django
    from django.apps import apps

    if apps.ready:
        return
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")
    sys.path.insert(0, str(REPO_ROOT / "src"))
    sys.path.insert(0, str(REPO_ROOT))
    django.setup()


def _iter_shells():
    """Every shipped shell template, RECURSIVELY.

    ``rglob``, not ``glob``: a non-recursive scan would silently drop a
    future shell shipped in a subdirectory from the manifest rather than
    failing loudly, defeating the drift test's whole purpose (a manifest
    that is "successfully" stale). Matches ``brickwork.examples.
    list_examples()``'s own ``rglob("*.html")`` walk of the examples tree.

    Yields ``(namespace, rel_name, rel_path, path)``: ``rel_name`` is the
    catalogue name qualifier (POSIX, ``.html`` stripped) and ``rel_path`` is
    the real path relative to the root (POSIX, WITH ``.html``, the exact
    suffix a Django template ref needs), so the caller never has to
    re-derive either from the bare filename, which is what would silently
    break for a nested file.
    """
    for namespace, root in _SHELL_ROOTS:
        for path in sorted(root.rglob("*.html")):
            rel_path = path.relative_to(root)
            yield namespace, rel_path.with_suffix("").as_posix(), rel_path.as_posix(), path


def _iter_components():
    """Every shipped component template, RECURSIVELY (see ``_iter_shells``).

    Only files whose own basename starts with ``_`` count as a component
    (matching the existing ``_*.html`` convention: a private render target,
    never `{% extends %}`able directly), so ``rglob`` plus an explicit
    basename check replaces the non-recursive ``glob("_*.html")``, which
    could not express "recursive AND underscore-prefixed" in one pattern.
    """
    for namespace, root in _COMPONENT_ROOTS:
        for path in sorted(root.rglob("*.html")):
            if not path.name.startswith("_"):
                continue
            rel_path = path.relative_to(root)
            # Strip the leading underscore from the file's own basename only
            # (matching today's manifest names, e.g. "button" for
            # _button.html); any subdirectory segments stay verbatim so a
            # nested component's qualified name stays unambiguous.
            *parts, leaf = rel_path.with_suffix("").parts
            rel_name = "/".join([*parts, leaf.removeprefix("_")])
            yield namespace, rel_name, rel_path.as_posix(), path


def _raise_on_duplicate_names(items: list[dict]) -> None:
    """Fail loudly on a duplicate catalogue ``name``, rather than overwrite it.

    A shell or component's catalogue name (``shell/<rel path>``,
    ``component/<rel path>``) is built from the path relative to ITS OWN
    root, with no namespace qualifier, matching every name already shipped
    today. That is safe only because the two shell roots and the two
    component roots (``brickwork`` and ``brickwork_marketing``) have never
    shipped a same-relative-path file: if they ever did (for example, both
    trees shipping their own ``_hero.html``), both would resolve to the
    identical catalogue name ``component/hero``, and the in-package reader's
    name index (a plain dict keyed on ``name``, built by iterating
    ``items()``) would silently keep only whichever one was appended last,
    with no error anywhere.

    No such collision exists in the shipped tree today (verified: this
    check runs on every generation and has never fired). Rather than
    namespace every existing name by root pre-emptively (a breaking rename
    of all 40 component and 5 shell catalogue names for a collision that
    has never occurred), this turns the actual failure mode, a silent
    overwrite, into a loud one: the FIRST PR that introduces a real
    collision fails the generator immediately, with both colliding template
    paths named, rather than shipping a manifest that quietly drops one of
    them.
    """
    seen: dict[str, str] = {}
    for entry in items:
        name = entry["name"]
        template_path = entry.get("templatePath", "<no templatePath>")
        if name in seen:
            raise ValueError(
                f"catalogue name collision: '{name}' is produced by both "
                f"{seen[name]!r} and {template_path!r}. Two different shipped "
                f"templates cannot resolve to the same catalogue-manifest name; "
                f"disambiguate one of them (for example, by giving the "
                f"catalogue name its root namespace) before regenerating."
            )
        seen[name] = template_path


def _iter_examples():
    """Every shipped example, split into archetypes (whole pages) and sections."""
    from brickwork import examples as examples_module

    root = examples_module.EXAMPLES_ROOT
    for rel_name in examples_module.list_examples():
        path = root / rel_name
        parts = Path(rel_name).parts
        if parts[0] == "sections":
            # sections/<type>/<variant>.html
            kind = "section"
            family = None
        else:
            # base.html, app/*.html, auth/*.html, marketing/*.html
            kind = "archetype"
            top = parts[0] if len(parts) > 1 else None
            family = _FAMILY_BY_EXAMPLE_DIR.get(top)
        yield kind, family, rel_name, path


def _load_template_manifest() -> dict:
    return json.loads(TEMPLATE_MANIFEST_PATH.read_text(encoding="utf-8"))


def _tag_names_by_template(template_manifest: dict) -> dict[str, str]:
    """Map a tag-consumed component's template ref back to its tag name.

    ``template-manifest.json`` records a block's ``declaredIn`` and
    ``consumption`` ("tag" for a private inclusion_tag render target) but not
    the tag's own registered name (the manifest is block/partial-keyed, and
    a block name and a tag name are different namespaces). The registration
    call sites are the only mechanical source for that name, exactly as
    ``generate_template_manifest.py``'s own ``_inclusion_tag_targets_from_
    source`` reads them; this repeats that grep against the same decorator
    call sites rather than importing that script (kept a standalone,
    single-purpose generator, matching this repo's one-script-per-artefact
    convention).
    """
    targets: dict[str, str] = {}
    for py_file in sorted((SRC / "brickwork" / "templatetags").glob("*.py")):
        text = py_file.read_text(encoding="utf-8")
        for match in re.finditer(r'@register\.inclusion_tag\(\s*"([^"]+)"[^)]*\)\s*\ndef (\w+)\(', text):
            template_ref, func_name = match.group(1), match.group(2)
            targets[template_ref] = func_name
    return targets


_BW_TAG_CALL_RE = re.compile(r"\{%-?\s*(bw_[a-z_]+)\b")


def _bw_tag_calls_from_source(text: str) -> set[str]:
    """Every ``{% bw_* %}`` tag name called in a template's own source text.

    Covers the components ONLY reachable via a tag (``_button.html`` and
    friends): they never appear as an ``IncludeNode``/``ExtendsNode`` target,
    so their usage is only visible as a tag call in the source, not the
    compiled node tree (Django exposes no public node class or attribute
    naming a custom simple/inclusion tag call, unlike ``BlockNode.name`` or
    ``IncludeNode.template``, so there is no node-tree route to fall back
    to). A regex over source text is the wrong tool for block/partial NAMES
    (``generate_template_manifest.py``'s own docstring explains why: prose in
    a ``{% comment %}`` is textually indistinguishable from a real tag); the
    same risk does not apply here, since brickwork's own examples never
    mention a ``{% bw_* %}`` call inside a comment (verified against the
    shipped tree). This stays a targeted, single-purpose extraction (call
    syntax only, ``{% <name>`` at a tag boundary), not a general name scan.
    """
    return set(_BW_TAG_CALL_RE.findall(text))


def _is_bare_variable_token(token: str) -> bool:
    """True when a compiled ``FilterExpression`` token is a variable reference.

    ``FilterExpression.token`` for a quoted string keeps its quotes
    (``'"Foo"'``), for a bare number is just digits, and for a variable
    reference is a bare identifier with neither. A bare identifier can only
    resolve from the render context (Django templates have no other way to
    define a name outside ``{% with %}``, which is a different node).
    """
    if not token or token[0] in "\"'" or token in ("True", "False", "None"):
        return False
    try:
        float(token)
    except ValueError:
        return True
    return False


_CONTEXT_CARRYING_TAG_RE = re.compile(r"\{%-?\s*(?:bw_form|bw_field_widget|bw_nav|bw_nav_header|bw_nav_rail)\b")


def _is_literal_or_local_token(token: str, local_names: frozenset[str]) -> bool:
    """True when a compiled token needs nothing from the render context.

    Either it is not a bare-variable token at all (``_is_bare_variable_token``
    is false: a quoted string, a number, ``True``/``False``/``None``), or it
    IS a bare variable but the name it names is itself already local in the
    CURRENT scope (bound by an enclosing ``{% with %}`` whose own right-hand
    side satisfied this same rule, or by an earlier ``{% firstof ... as %}``
    in the same nodelist). This is the RHS condition a with/firstof binding's
    own value must pass before the name it defines can be treated as local
    (see ``_scan_requires_context``): a binding that copies an external
    context variable straight through (``{% with heading=external_heading %}``)
    does NOT satisfy it, so the bound name stays context-sourced.
    """
    return not _is_bare_variable_token(token) or token in local_names


def _scan_requires_context(node_list, text: str, local_names: frozenset[str]) -> bool:
    """Walk ``node_list`` depth-first, threading a SCOPED set of local names.

    ``local_names`` is exactly the names safely treated as "not context
    requirements" at THIS point in the tree: names bound by an enclosing
    ``{% with %}`` (only while inside that block's own nodelist, per Django's
    real scoping, ``WithNode.render`` pushes and the context manager pops) or
    by an earlier sibling ``{% firstof ... as %}`` (not block-scoped: the
    binding is a plain statement visible to everything AFTER it in the same
    nodelist, matching how the compiled node list executes top to bottom).

    Recursion follows ``Node.child_nodelists`` exactly as Django's own
    ``Node.get_nodes_by_type`` does (verified against ``IfNode``, whose
    ``child_nodelists = ("nodelist",)`` resolves through its ``nodelist``
    property, itself built from ``NodeList(self)``, which flattens the
    node's ``__iter__`` across every branch rather than looping on ``self``),
    so a nested ``{% if %}``/``{% for %}``/``{% block %}`` correctly inherits
    whatever is local in its enclosing scope without hand-listing every tag.

    Three mechanical signals, matching the ways brickwork's own examples take
    dynamic data a Django template cannot build inline (per the ``brickwork``
    skill's documented split):

    1. A ``{% for x in VAR %}`` loop whose sequence is a bare variable not
       itself local (the ``sections/listing/*`` shape: the file loops over
       ``entries`` with no local definition of it).
    2. An ``{% include ... with k=VAR %}`` argument whose value is a bare
       variable not itself local (the ``sections/features/icon-grid.html``
       shape: ``items=features``, passing a context-sourced list straight
       through).
    3. A call to one of the tags that only ever take a context-sourced bound
       object (``bw_form``/``bw_field_widget`` always take a Django ``Form``/
       ``BoundField``; ``bw_nav``/``bw_nav_header``/``bw_nav_rail`` always
       take the resolved nav tree): these take a positional argument, which
       ``IncludeNode.extra_context`` cannot see (it is not an include), so
       they are checked once, globally, by the caller rather than here.

    This is a deliberately mechanical, not exhaustive, signal covering the
    call shapes brickwork's own shipped tree actually uses; it is not a
    general "does this template need anything" analyser. docs/CATALOGUE.md
    records this as a known, deliberate imprecision rather than a hidden one.
    """
    from django.template.defaulttags import FirstOfNode, ForNode, WithNode
    from django.template.loader_tags import IncludeNode

    scope = local_names
    for node in node_list:
        if isinstance(node, ForNode):
            if not _is_literal_or_local_token(getattr(node.sequence, "token", ""), scope):
                return True
            if _scan_requires_context(node.nodelist_loop, text, scope):
                return True
            if _scan_requires_context(node.nodelist_empty, text, scope):
                return True
            continue

        if isinstance(node, IncludeNode):
            # A leaf reference, never a container: its "children" are the
            # INCLUDED template's own compiled tree (a separate parse this
            # generator never crosses into), not inline content in THIS
            # node list, so there is nothing of this node's own to recurse
            # into here (the inherited `child_nodelists = ("nodelist",)` is
            # Node's base-class default; IncludeNode never actually sets a
            # real `self.nodelist`, which is why following it unconditionally
            # raised AttributeError before this comment was written).
            for value in node.extra_context.values():
                if not _is_literal_or_local_token(getattr(value, "token", ""), scope):
                    return True
            continue

        if isinstance(node, FirstOfNode):
            # firstof's own render() never fails regardless of what its
            # arguments resolve to (ignore_failures=True per-argument, and
            # asvar is always assigned, "" in the worst case), so the RHS
            # rule here is deliberately an ANY, not with's ALL: at least one
            # argument must be literal-or-local to guarantee a defined
            # fallback that needs nothing from the render context. This is
            # base.html's real shape: `{% firstof bw_toast_position 'top-end'
            # as resolved %}` has one bare-variable argument and one string
            # literal, so the literal alone makes `resolved` safely local
            # even though `bw_toast_position` itself is context-sourced.
            args_ok = any(_is_literal_or_local_token(getattr(v, "token", ""), scope) for v in node.vars)
            if node.asvar and args_ok:
                scope = scope | {node.asvar}
            continue

        if isinstance(node, WithNode):
            rhs_tokens = (getattr(v, "token", "") for v in node.extra_context.values())
            rhs_ok = all(_is_literal_or_local_token(token, scope) for token in rhs_tokens)
            inner_scope = scope | set(node.extra_context) if rhs_ok else scope
            if _scan_requires_context(node.nodelist, text, inner_scope):
                return True
            # WithNode's own bindings are block-scoped: they do not extend
            # `scope` for siblings after the block, unlike firstof's asvar.
            continue

        for attr in node.child_nodelists:
            child = getattr(node, attr, None)
            if child and _scan_requires_context(child, text, scope):
                return True

    return False


def _requires_context(node_list, text: str) -> bool:
    """True if the example needs render-context data for its real content.

    Delegates the for/include/firstof/with walk to ``_scan_requires_context``
    (a single scoped pass, so a with-binding's locality is judged correctly
    per block rather than file-wide); the ``bw_form``/``bw_nav``-family tag
    check runs once here since those tags take a positional argument no
    node-tree scope tracking is relevant to (see that function's signal 3).
    """
    if _CONTEXT_CARRYING_TAG_RE.search(text):
        return True
    return _scan_requires_context(node_list, text, frozenset())


def _included_and_extended_refs(node_list) -> set[str]:
    from django.template.loader_tags import ExtendsNode, IncludeNode

    refs: set[str] = set()
    for node in node_list.get_nodes_by_type(IncludeNode):
        template = node.template
        token = getattr(template, "token", None) or getattr(template, "var", None)
        if isinstance(token, str):
            refs.add(token.strip("\"'"))
    for node in node_list.get_nodes_by_type(ExtendsNode):
        refs.add(node.parent_name.token.strip("\"'"))
    return refs


def build_manifest() -> dict:
    _setup_django()

    from django.template import Engine
    from django.template.backends.django import get_installed_libraries as get_default_libraries

    from brickwork import examples as examples_module

    template_manifest = _load_template_manifest()
    tag_names_by_template_ref = _tag_names_by_template(template_manifest)
    template_ref_by_tag_name = {v: k for k, v in tag_names_by_template_ref.items()}

    # template-manifest.json is block-keyed, so a template with no named
    # blocks at all (e.g. _spinner.html) has no entry there to read
    # consumption from. Recompute it per-template directly instead, reusing
    # the same tag/extends detection the block generator uses: tag-registered
    # templates are "tag"; a template whose own source self-extends
    # (documented "consumed via extending") is "extend"; everything else is
    # "include".
    include_primary_phrase = re.compile(r"consumed via \{%\s*include\s*%\}", re.IGNORECASE)

    def _self_extends_pattern(template_ref: str) -> re.Pattern[str]:
        return re.compile(r'\{%\s*extends\s+"' + re.escape(template_ref) + r'"\s*%\}')

    def _consumption(template_ref: str, text: str) -> str:
        if template_ref in tag_names_by_template_ref:
            return "tag"
        if _self_extends_pattern(template_ref).search(text) and not include_primary_phrase.search(text):
            return "extend"
        return "include"

    # Engine for the examples tree (off the loader path by design, per
    # brickwork.examples's own docstring; this is the ONLY supported way to
    # render/parse one). app_dirs=True so an example's own {% extends %} onto
    # a shipped shell resolves; libraries comes from get_default_libraries()
    # exactly as tests/test_examples.py's _example_engine() explains: a bare
    # Engine() does not inherit {% load static/i18n %} discovery.
    examples_engine = Engine(
        dirs=[str(examples_module.EXAMPLES_ROOT)],
        app_dirs=True,
        libraries=get_default_libraries(),
    )

    # First pass: parse every example and record what it references.
    example_refs: dict[str, dict] = {}
    for kind, family, rel_name, path in _iter_examples():
        text = path.read_text(encoding="utf-8")
        parsed = examples_engine.get_template(rel_name)
        refs = _included_and_extended_refs(parsed.nodelist)
        called_tag_names = _bw_tag_calls_from_source(text)
        refs |= {template_ref_by_tag_name[name] for name in called_tag_names if name in template_ref_by_tag_name}
        example_refs[rel_name] = {
            "kind": kind,
            "family": family,
            "refs": refs,
            "requiresContext": _requires_context(parsed.nodelist, text),
        }

    # usedByArchetypes / usedBySections: invert example_refs onto each
    # shell/component template_ref, split by example kind so a component
    # used only by sections (e.g. a marketing section component) does not
    # falsely claim archetype usage.
    used_by: dict[str, dict[str, list[str]]] = {}
    for rel_name, info in example_refs.items():
        bucket_key = "usedByArchetypes" if info["kind"] == "archetype" else "usedBySections"
        for ref in info["refs"]:
            used_by.setdefault(ref, {"usedByArchetypes": [], "usedBySections": []})
            used_by[ref][bucket_key].append(rel_name)

    # composesItems: the forward direction for each example (what it pulls in).
    def _compose_list(rel_name: str) -> list[str]:
        return sorted(example_refs[rel_name]["refs"])

    items: list[dict] = []

    for namespace, name, rel_path, path in _iter_shells():
        # template_ref is the real Django template ref: namespace plus the
        # path RELATIVE TO THE ROOT (rel_path, not the file's own bare
        # basename), so a nested shell's {% extends %}/{% include %}
        # cross-references resolve against the right path.
        template_ref = f"{namespace}/shell/{rel_path}"
        text = path.read_text(encoding="utf-8")
        usage = used_by.get(template_ref, {"usedByArchetypes": [], "usedBySections": []})
        items.append(
            {
                "name": f"shell/{name}",
                "kind": "shell",
                "family": None,
                "templatePath": template_ref,
                "docSource": template_ref,
                "consumption": _consumption(template_ref, text),
                "usedByArchetypes": sorted(usage["usedByArchetypes"]),
                "usedBySections": sorted(usage["usedBySections"]),
            }
        )

    for namespace, name, rel_path, path in _iter_components():
        template_ref = f"{namespace}/components/{rel_path}"
        text = path.read_text(encoding="utf-8")
        usage = used_by.get(template_ref, {"usedByArchetypes": [], "usedBySections": []})
        items.append(
            {
                "name": f"component/{name}",
                "kind": "component",
                "family": None,
                "templatePath": template_ref,
                "docSource": template_ref,
                "consumption": _consumption(template_ref, text),
                "usedByArchetypes": sorted(usage["usedByArchetypes"]),
                "usedBySections": sorted(usage["usedBySections"]),
            }
        )

    for rel_name, info in sorted(example_refs.items()):
        example_ref = f"examples/{rel_name}"
        items.append(
            {
                "name": example_ref,
                "kind": info["kind"],
                "family": info["family"],
                "templatePath": example_ref,
                "docSource": example_ref,
                "requiresContext": info["requiresContext"],
                "composesItems": _compose_list(rel_name),
            }
        )

    items.sort(key=lambda entry: (entry["kind"], entry["name"]))
    _raise_on_duplicate_names(items)

    counts = {
        "shells": sum(1 for i in items if i["kind"] == "shell"),
        "components": sum(1 for i in items if i["kind"] == "component"),
        "sections": sum(1 for i in items if i["kind"] == "section"),
        "archetypes": sum(1 for i in items if i["kind"] == "archetype"),
    }

    # families: package truth only (CATALOGUE.md section 8). Every family
    # with at least one shipped archetype or section, with a mechanical
    # shipped-coverage count. Deliberately carries NO status field
    # ("shipping"/"planned") and NO wave assignment: those are roadmap
    # truth (ROADMAP.md prose with no shipped-tree signal to regenerate
    # from), not package truth, and baking them into a versioned wheel
    # would go stale for the life of whatever pin installed it, with no
    # mechanism here to catch or correct that. A family absent from this
    # list simply has no shipped item yet; see ROADMAP.md for its wave.
    family_names = sorted({i["family"] for i in items if i.get("family")})
    families = [
        {
            "name": family_name,
            "archetypeCount": sum(1 for i in items if i["kind"] == "archetype" and i["family"] == family_name),
            "sectionCount": sum(1 for i in items if i["kind"] == "section" and i["family"] == family_name),
        }
        for family_name in family_names
    ]

    return {
        "$schema": "https://brickwork.icvoss.dev/catalogue-manifest/v1",
        "version": 1,
        "description": (
            "brickwork catalogue taxonomy (plan decision D8): family, kind, "
            "archetype/section usage and doc pointers for every shipped shell, "
            "component, section example and archetype example. A sibling of "
            "template-manifest.json, never merged into it: this file is "
            "descriptive catalogue metadata, not a BR-BW-VER-001 semver "
            "contract, and may evolve in minors (D8). 'family' is a catalogue "
            "taxonomy field only (O1): it is never a package API identifier. "
            "'families' lists shipped-coverage package truth only (which "
            "families have shipped items, and how many); it carries no "
            "planned/wave status, which is roadmap truth read from "
            "ROADMAP.md instead (see docs/CATALOGUE.md section 8). "
            "Generated by scripts/generate_catalogue_manifest.py from the "
            "shipped template and examples trees; do not edit by hand."
        ),
        "counts": counts,
        "families": families,
        "items": items,
    }


def write_manifest(output_path: Path) -> dict:
    """Build the manifest and write it to ``output_path``, the ONE code path.

    Both ``main()`` and the drift test call this, so the test compares bytes
    the generator actually wrote (via a temp path), never a second,
    hand-duplicated ``json.dumps(...)`` expression that could silently
    diverge from what ``main()`` really produces (a changed ``separators``,
    ``ensure_ascii``, or trailing-newline convention here would otherwise go
    undetected by a test re-implementing its own serialisation).
    """
    manifest = build_manifest()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    manifest = write_manifest(MANIFEST_PATH)
    counts = manifest["counts"]
    print(
        f"catalogue manifest written: {counts['shells']} shells, {counts['components']} components, "
        f"{counts['sections']} sections, {counts['archetypes']} archetypes -> {MANIFEST_PATH}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
