#!/usr/bin/env python3
"""Generate ``template-manifest.json``: the template contract surface.

Run from the repo root, with the package importable (the CI ``test`` job's
Python environment already satisfies this):

    DJANGO_SETTINGS_MODULE=tests.settings PYTHONPATH=src:. \\
        python scripts/generate_template_manifest.py

BR-BW-TPL-001 makes every named ``{% block %}`` in a shipped shell/component
and every ``{% partialdef %}`` semver-public: renaming or removing one must
follow the BR-BW-VER-001 parallel-support cycle, never a silent change. This
script is the ONLY thing that writes ``template-manifest.json``: it walks the
real shipped template tree (``brickwork/templates/brickwork`` and
``brickwork/marketing/templates/brickwork_marketing``), parses each file with
Django's own template engine, and records every block/partial name it finds by
walking the COMPILED node tree, never a regex over the source text.

A regex approach was tried and rejected during design: a `{% block %}` name
mentioned in prose inside a `{% comment %}` (several templates cross-reference
another template's block by name, e.g. "matching _alert.html's
`{% block alert_body %}` convention") is textually indistinguishable from a
real tag without a real parser, and produced false positives for
`_card.html`, `_page_header.html`, and `_nav_rail.html` in early testing. The
compiled `NodeList` route excludes comment content correctly (Django's own
`{% comment %}` tag discards its contents at parse time) and is immune to
this class of error by construction.

``do not edit by hand``: this file is regenerated by this script; the ``test``
CI job re-runs it and fails the build on any diff (see ``.github/workflows/ci.yml``,
mirroring the ``frontend-build`` job's token-artefact drift gate).
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "src"
DIST = SRC / "brickwork" / "static" / "brickwork" / "dist"
MANIFEST_PATH = DIST / "template-manifest.json"

# The two shipped, semver-governed template roots (BR-BW-TPL-001). Deliberately
# NOT `examples/`: BR-BW-EX-003 states outright that no part of an example's
# internal structure is a versioned contract, since nothing installed resolves
# it (ADR-056). Deliberately NOT `patterns/`/`pages/`: removed from the loader
# path at 2.0.0 (ADR-056) and carry no live block surface to extract.
_ROOTS = (
    ("brickwork", SRC / "brickwork" / "templates" / "brickwork"),
    ("brickwork_marketing", SRC / "brickwork" / "marketing" / "templates" / "brickwork_marketing"),
)

# A template's own leading {% comment %} documents "Consumed by EXTENDING" (or
# equivalent) for the handful of components whose ONLY customisation path is a
# consumer template opening `{% extends "<this template's own path>" %}` and
# filling named blocks (_modal.html, _slide_over.html, _tooltip.html,
# _bulk_actions_bar.html). A structural include-consumed component
# (_card.html, _page_header.html) ALSO documents this pattern as a secondary
# escape hatch for block-filling, but says so alongside "consumed via
# {% include %}" as its PRIMARY path; that phrase is the tie-breaker.
_INCLUDE_PRIMARY_PHRASE = re.compile(r"consumed via \{%\s*include\s*%\}", re.IGNORECASE)


def _setup_django() -> None:
    """Populate the app registry if it is not already (idempotent).

    Safe to call both from the command-line entry point (no app registry yet)
    and from a pytest-django test (the registry is already populated by the
    time a test runs): ``apps.populate()`` returns immediately once the
    registry is ready, so a second ``django.setup()`` call is a no-op rather
    than a re-import.
    """
    import django
    from django.apps import apps

    if apps.ready:
        return
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")
    sys.path.insert(0, str(REPO_ROOT / "src"))
    sys.path.insert(0, str(REPO_ROOT))
    django.setup()


def _self_extends_pattern(namespace: str, rel_path: str) -> re.Pattern[str]:
    template_ref = f"{namespace}/{rel_path}"
    return re.compile(r'\{%\s*extends\s+"' + re.escape(template_ref) + r'"\s*%\}')


def _inclusion_tag_targets_from_source() -> frozenset[str]:
    """Fallback/primary source: grep the registered decorator calls directly.

    Reading Django's live tag registry does not expose the inclusion
    template's path as public API (the closure captures it privately), so the
    reliable mechanical source is the decorator call itself:
    ``@register.inclusion_tag("brickwork/...html", ...)``. This is still
    reading the real registration site, not a hand-authored list: any new
    ``inclusion_tag`` call is picked up automatically, and it is a syntax
    error for the decorator argument to name a path that does not exist,
    which the drift test below also checks.
    """
    targets: set[str] = set()
    pattern = re.compile(r'@register\.inclusion_tag\(\s*"([^"]+)"')
    for py_file in sorted((SRC / "brickwork" / "templatetags").glob("*.py")):
        targets.update(pattern.findall(py_file.read_text(encoding="utf-8")))
    return frozenset(targets)


def _classify_consumption(namespace: str, rel_path: str, text: str, tag_targets: frozenset[str]) -> str:
    template_ref = f"{namespace}/{rel_path}"
    if template_ref in tag_targets:
        return "tag"
    if _self_extends_pattern(namespace, rel_path).search(text) and not _INCLUDE_PRIMARY_PHRASE.search(text):
        return "extend"
    return "include"


def _iter_templates():
    for namespace, root in _ROOTS:
        for path in sorted(root.rglob("*.html")):
            rel_path = path.relative_to(root).as_posix()
            yield namespace, rel_path, path


def build_manifest() -> dict:
    _setup_django()

    from django.template.defaulttags import PartialDefNode
    from django.template.loader import get_template
    from django.template.loader_tags import BlockNode, ExtendsNode

    tag_targets = _inclusion_tag_targets_from_source()

    # First pass: every template's OWN block/partial declarations (the nodes
    # in its own source, not a resolved ancestor's), plus its extends target
    # if any. Walking ExtendsNode.nodelist (rather than the top-level
    # nodelist, which for an extending template is just [ExtendsNode]) gives
    # exactly the blocks THIS file's own source declares or overrides,
    # without eagerly resolving the parent chain.
    per_template: dict[str, dict] = {}
    for namespace, rel_path, path in _iter_templates():
        template_ref = f"{namespace}/{rel_path}"
        text = path.read_text(encoding="utf-8")
        django_template = get_template(template_ref).template
        extends_nodes = django_template.nodelist.get_nodes_by_type(ExtendsNode)
        if extends_nodes:
            own_nodelist = extends_nodes[0].nodelist
            extends_ref = extends_nodes[0].parent_name.token
        else:
            own_nodelist = django_template.nodelist
            extends_ref = None
        own_blocks = [n.name for n in own_nodelist.get_nodes_by_type(BlockNode)]
        own_partials = [
            {"name": n.partial_name, "inline": n.inline} for n in own_nodelist.get_nodes_by_type(PartialDefNode)
        ]
        per_template[template_ref] = {
            "namespace": namespace,
            "path": rel_path,
            "extends": extends_ref,
            "own_blocks": own_blocks,
            "own_partials": own_partials,
            "consumption": _classify_consumption(namespace, rel_path, text, tag_targets),
        }

    # Second pass: a block name is "introduced" by a template if it is not
    # already declared by that template's own extends-ancestor. A shared name
    # with no common ancestor declaring it (e.g. "content", independently
    # declared by shell/app.html, shell/auth.html, shell/centred.html and
    # brickwork_marketing/shell/marketing.html, each its own extension point
    # off shell/base.html, which itself does not declare "content") is
    # introduced by EVERY template that declares it: block ownership is a
    # set, not a single owner, because Django inheritance legitimately lets
    # sibling leaf templates each offer the same-named override point.
    def _ancestor_blocks(template_ref: str) -> set[str]:
        entry = per_template.get(template_ref)
        if entry is None or entry["extends"] is None:
            return set()
        parent = per_template.get(entry["extends"])
        if parent is None:
            return set()
        return set(parent["own_blocks"]) | _ancestor_blocks(entry["extends"])

    blocks: dict[str, list[str]] = {}
    partials: dict[str, dict] = {}
    consumption: dict[str, str] = {}

    for template_ref, entry in per_template.items():
        consumption[template_ref] = entry["consumption"]
        ancestor_blocks = _ancestor_blocks(template_ref)
        for name in entry["own_blocks"]:
            if name in ancestor_blocks:
                continue  # inherited override, not a new declaration here
            blocks.setdefault(name, [])
            if template_ref not in blocks[name]:
                blocks[name].append(template_ref)
        for partial in entry["own_partials"]:
            name = partial["name"]
            if name in partials:
                raise ValueError(
                    f"partial '{name}' is declared in both {partials[name]['declaredIn']} "
                    f"and {template_ref}; partial names must be unique across the shipped tree"
                )
            partials[name] = {"declaredIn": template_ref, "inline": partial["inline"]}

    block_entries = [
        {
            "name": name,
            "declaredIn": sorted(owners),
            "consumption": sorted({consumption[owner] for owner in owners}),
        }
        for name, owners in sorted(blocks.items())
    ]
    partial_entries = [
        {
            "name": name,
            "declaredIn": info["declaredIn"],
            "inline": info["inline"],
            "consumption": consumption[info["declaredIn"]],
        }
        for name, info in sorted(partials.items())
    ]

    return {
        "$schema": "https://brickwork.icvoss.dev/template-manifest/v1",
        "version": 1,
        "description": (
            "brickwork template contract: every named {% block %} in a shipped shell "
            "or component, and every {% partialdef %} in a shipped component "
            "(BR-BW-TPL-001). Names are semver-public: renaming or removing one "
            "requires the BR-BW-VER-001 parallel-support cycle and a major bump, "
            "never a silent change. Generated by scripts/generate_template_manifest.py "
            "from the shipped template tree; do not edit by hand."
        ),
        "blocks": block_entries,
        "partials": partial_entries,
        "deprecated": [
            {
                "kind": "block",
                "name": "empty_state_action",
                "declaredIn": "brickwork/components/_empty_state.html",
                "supersededBy": "action",
                "removedAt": "4.0.0",
                "note": (
                    "Superseded by the concise 'action' block (CMP-032). Both "
                    "render while deprecated (BR-BW-VER-001 parallel support); "
                    "a caller migrating to the concise name fills 'action' only."
                ),
            },
        ],
    }


def check_contract_stability(
    baseline: dict,
    current_manifest: dict,
    committed_manifest: dict | None = None,
) -> list[str]:
    """Compare a checked-in baseline against a freshly generated manifest.

    Returns one instructive violation message per block/partial name that
    disappeared (removed or renamed) without a covering ``deprecated`` entry.
    Additive changes (a brand new name) are never a violation: BR-BW-TPL-001
    only constrains removing or renaming an EXISTING name, and adding one is a
    MINOR change. A name that legitimately moved to ``deprecated`` in the
    current manifest, WITHOUT disappearing from ``blocks``/``partials`` (the
    BR-BW-VER-001 parallel-support shape: both the old and new name render),
    is also never a violation.

    The two collections are compared independently (a block name and a
    partial name occupy separate namespaces in Django's template language, so
    ``blocks``/``partials`` are checked as two disjoint sets, never merged).

    ``committed_manifest`` is the manifest as checked in before this run, used
    only to tell the author WHICH template the vanished name used to live in.
    The baseline deliberately stores bare names (it is hand-maintained, and a
    name is the contract; the path is not), so provenance is recovered from the
    committed manifest's ``declaredIn`` instead of duplicating it into the
    baseline. Omitted, the message simply loses that one sentence.
    """
    violations: list[str] = []
    current_deprecated_names = {entry["name"] for entry in current_manifest["deprecated"]}
    baseline_deprecated_names = set(baseline["deprecated"])
    previously_declared_in: dict[tuple[str, str], list[str]] = {}
    if committed_manifest is not None:
        for kind_key, kind_label in (("blocks", "block"), ("partials", "partial")):
            for entry in committed_manifest.get(kind_key, []):
                previously_declared_in[(kind_label, entry["name"])] = entry.get("declaredIn", [])

    for kind, baseline_names, current_entries in (
        ("block", baseline["blocks"], current_manifest["blocks"]),
        ("partial", baseline["partials"], current_manifest["partials"]),
    ):
        current_names = {entry["name"] for entry in current_entries}
        for name in sorted(baseline_names):
            if name in current_names:
                continue
            if name in baseline_deprecated_names and name in current_deprecated_names:
                # Removed from the live surface but still tracked as
                # deprecated: this is only correct at the major bump that
                # actually removes it, which is exactly when a human updates
                # this baseline in the same PR; nothing to check here.
                continue
            declared_in = previously_declared_in.get((kind, name), [])
            provenance = (
                f" It was last declared in {', '.join(declared_in)}." if declared_in else ""
            )
            violations.append(
                f"The {kind} '{name}' is in the committed contract baseline "
                f"(tests/template_contract_baseline.json) but is no longer in the "
                f"generated template manifest. BR-BW-TPL-001 makes every named "
                f"{{% block %}}/{{% partialdef %}} name semver-public: it cannot be "
                f"renamed or removed silently.{provenance}\n"
                f"  Fix, one of:\n"
                f"  1. You renamed or removed '{name}' by mistake: restore the "
                f"original name.\n"
                f"  2. You meant to deprecate it (BR-BW-VER-001 parallel support): "
                f"keep the old {kind} rendering alongside the new one, add an entry "
                f"to the manifest generator's 'deprecated' list naming the "
                f"superseding name and the major version it is removed at, then "
                f"regenerate the manifest (this keeps '{name}' present in both "
                f"the manifest and this baseline until the major bump that "
                f"actually drops it).\n"
                f"  3. This is a deliberate breaking change: it may only ship in a "
                f"MAJOR release. Update tests/template_contract_baseline.json in "
                f"the same PR as the major bump (move '{name}' out of the "
                f"baseline entirely, not just out of 'deprecated')."
            )
    return violations


def main() -> int:
    manifest = build_manifest()
    DIST.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(
        f"template manifest written: {len(manifest['blocks'])} blocks, {len(manifest['partials'])} partials -> {MANIFEST_PATH}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
